# Uncomment the next line to define a global platform for your project

 platform :ios, '8.0'

target 'CapApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CapApp

  target 'CapAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CapAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Firebase/Core'
end
